"""Rename column initial_quantity to stock in products

Revision ID: 3b4c58be09de
Revises: 0fee33306a3b
Create Date: 2024-06-15 19:06:46.520602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4c58be09de'
down_revision: Union[str, None] = '0fee33306a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.drop_column('products', 'initial_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('initial_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
