"""Added user and client

Revision ID: 70577147e54b
Revises: 2bf72ce75d31
Create Date: 2024-06-14 18:34:25.685375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70577147e54b'
down_revision: Union[str, None] = '2bf72ce75d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_role', table_name='clients')
    op.drop_column('clients', 'role')
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_clients_role', 'clients', ['role'], unique=False)
    # ### end Alembic commands ###
